server:
  port: 8085

dam:
  base-url: http://localhost:3000/
  client-id: local-dam-client-id
  client-secret: local-dam-client-secret
idp:
  base-url: http://localhost:3001/
  client-id: local-dam-client-id
  client-secret: local-dam-client-secret

ddap:
  public-uri: http://localhost:8085
  cors:
    origins: "http://localhost:4200"

spring:
  security:
    user:
      name: "dev"
      password: "dev"
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/api/cafevariome/**
          filters:
            - StripPrefix=2
            - Logging
          uri: https://beacon.cafevariome.org
        - predicates:
            - Path=/dam/**
          filters:
            - AddRequestParameter=clientId,${dam.client-id}
            - AddRequestParameter=clientSecret,${dam.client-secret}
            - SetBearerTokenFromCookie
            - Logging
          uri: ${dam.base-url}
        - predicates:
            - Path=/identity/v1alpha/passport
          filters:
            - AddRequestParameter=clientId,${idp.client-id}
            - AddRequestParameter=clientSecret,${idp.client-secret}
            - Logging
          uri: ${idp.base-url}
        - predicates:
            - Path=/identity/**
          filters:
            - AddRequestParameter=clientId,${idp.client-id}
            - AddRequestParameter=clientSecret,${idp.client-secret}
            - Logging
          uri: ${idp.base-url}
