dam:
  base-url: http://localhost:3000/
  client-id: local-dam-client-id
  client-secret: local-dam-client-secret

ddap:
  cors:
    origins: "http://localhost:4200"

spring:
  security:
    user:
      name: "dev"
      password: "dev"
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/dam/**
          filters:
            - AddRequestParameter=clientId,${dam.client-id}
            - AddRequestParameter=clientSecret,${dam.client-secret}
            - Logging
          uri: ${dam.base-url}
